using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Picklr.Models
{
    // Named PicklrProgram to avoid a name collision with the top-level Program class
    // generated by .NET's top-level statements feature.
    public class PicklrProgram
    {
        [Key]
        public int ProgramID { get; set; }

        [Required(ErrorMessage = "Please enter a program name.")]
        public string Name { get; set; } = string.Empty;

        public string Description { get; set; } = string.Empty;

        [Range(0, 10000, ErrorMessage = "Fee must be between 0 and 10000.")]
        public decimal Fee { get; set; }

        // Comma-delimited days this program runs, e.g. "Friday,Saturday,Sunday"
        public string AvailableDays { get; set; } = string.Empty;

        [Required(ErrorMessage = "Please select a club.")]
        [ForeignKey(nameof(Club))]
        public int ClubID { get; set; }

        public Club? Club { get; set; }
    }
}
